FROM node:20.11.1-alpine
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

RUN pnpm install --global turbo@1.12.4

COPY . .

RUN turbo prune app-avatax --docker

RUN pnpm install --frozen-lockfile --filter=app-avatax

CMD pnpm dev --filter=app-avatax
