packages:
  - apps/*
  - packages/*
  - templates/*
onlyBuiltDependencies:
  - "@sentry/cli"
  - core-js
  - esbuild
  - highlight.js
  - protobufjs
  - sharp
catalog:
  "@opentelemetry/api": 1.9.0
  "@opentelemetry/api-logs": 0.57.2
  "@opentelemetry/exporter-trace-otlp-http": 0.57.2
  "@opentelemetry/exporter-metrics-otlp-http": 0.57.2
  "@opentelemetry/instrumentation": 0.57.2
  "@opentelemetry/instrumentation-aws-sdk": 0.49.1
  "@opentelemetry/instrumentation-http": 0.57.2
  "@opentelemetry/resources": 1.30.1
  "@opentelemetry/sdk-logs": 0.57.2
  "@opentelemetry/sdk-trace-node": 1.30.1
  "@opentelemetry/semantic-conventions": 1.30.0
  "@opentelemetry/sdk-metrics": 1.30.1
  "@vercel/otel": 1.10.1
  "@sentry/cli": 1.77.3
  "@sentry/nextjs": 9.8.0
  eslint: 9.23.0
  "@saleor/app-sdk": 1.1.1
  urql: 4.0.4
  next: 15.2.4
  react: 18.2.0
  react-dom: 18.2.0
  "@saleor/macaw-ui": 1.1.10
  zod: 3.21.4
  "@trpc/client": 10.43.1
  "@trpc/next": 10.43.1
  "@trpc/server": 10.43.1
  "@trpc/react-query": 10.43.1
  "modern-errors": 7.0.1
  "modern-errors-serialize": 6.1.0
  "neverthrow": 6.2.1
  "dynamodb-toolbox": 2.6.4
  "@aws-sdk/lib-dynamodb": 3.651.1
  "@aws-sdk/client-dynamodb": 3.651.1
  "@aws-sdk/util-dynamodb": 3.651.1
  "@vitest/coverage-v8": 3.1.1
  "@t3-oss/env-nextjs": 0.11.1
  "react-hook-form": 7.43.9
  "zod-validation-error": 3.4.0
  "vite": 6.2.4
  "vite-tsconfig-paths": 5.1.4
  "vitest": 3.1.1
  "@hookform/resolvers": 3.3.1
  "usehooks-ts": 2.9.1
  "tsx": 4.19.3
  "typescript": 5.8.2
  # TODO Maybe this should be part of @saleor/eslint package
  "eslint-plugin-n": 17.16.2
  "graphql": 16.7.1
  "graphql-tag": 2.12.6
  "json-schema-to-typescript": 15.0.4
  "next-test-api-route-handler": 4.0.16