packages:
  - apps/*
  - packages/*
  - templates/*

onlyBuiltDependencies:
  - "@sentry/cli"
  - esbuild
  - highlight.js
  - protobufjs

catalog:
  "@opentelemetry/api": 1.9.0
  "@opentelemetry/api-logs": "0.57.2"
  "@opentelemetry/exporter-trace-otlp-http": "0.57.2"
  "@opentelemetry/instrumentation": "0.57.2"
  "@opentelemetry/instrumentation-aws-sdk": "0.49.1"
  "@opentelemetry/instrumentation-http": "0.57.2"
  "@opentelemetry/resources": "1.30.1"
  "@opentelemetry/sdk-logs": "0.57.2"
  "@opentelemetry/sdk-trace-node": "1.30.1"
  "@opentelemetry/semantic-conventions": "1.30.0"
  "@vercel/otel": "1.10.1"
  "@sentry/cli": "2.32.1"
  "@sentry/nextjs": "7.117.0"
  "@sentry/node": "7.117.0"
  "eslint": "8.57.0"
  "@saleor/app-sdk": "0.52.0"
  "urql": "4.0.4"
  "next": "14.2.3"
  "react": "18.2.0"
  "react-dom": "18.2.0"
  "@saleor/macaw-ui": "1.1.10"
  "zod": "3.21.4"
  "@trpc/client": "10.43.1"
  "@trpc/next": "10.43.1"
  "@trpc/server": "10.43.1"
  "@trpc/react-query": "10.43.1"
