export const ObservabilityAttributes = {
  SALEOR_API_URL: "saleorApiUrl",
  SALEOR_VERSION: "saleorVersion",
  CHANNEL_SLUG: "channelSlug",
  TRANSACTION_ID: "transactionId",
  CONFIGURATION_ID: "configurationId",
  ORDER_ID: "orderId",
  CHECKOUT_ID: "checkoutId",
  COMMIT_SHA: "git.commit.sha",
  REPOSITORY_URL: "git.repository_url",
  VERCEL_ENV: "vercel.env",
  PATH: "path",
  SALEOR_EVENT: "saleorEvent",
  TENANT_DOMAIN: "saleor.environment_domain",
} as const;
