schema: backend/monitoring/schema.graphql
documents: [src/**/*.tsx]
extensions:
  codegen:
    overwrite: true
    generates:
      generated/graphql.ts:
        config:
          dedupeFragments: true
        plugins:
          - typescript
          - typescript-operations
          - typed-document-node
      generated/schema.graphql:
        plugins:
          - schema-ast
