import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

// https://env.t3.gg/docs/recipes#booleans
const booleanSchema = z
  .string()
  .refine((s) => s === "true" || s === "false")
  .transform((s) => s === "true");

export const env = createEnv({
  client: {
    NEXT_PUBLIC_SENTRY_DSN: z.string().optional(),
  },
  server: {
    ALLOWED_DOMAIN_PATTERN: z.string().optional(),
    APL: z.enum(["saleor-cloud", "file", "dynamodb"]).optional().default("file"),
    APP_API_BASE_URL: z.string().optional(),
    APP_IFRAME_BASE_URL: z.string().optional(),
    APP_LOG_LEVEL: z.enum(["fatal", "error", "warn", "info", "debug", "trace"]).default("info"),
    FILE_APL_PATH: z.string().optional(),
    MANIFEST_APP_ID: z.string().optional().default("saleor.app.product-feed"),
    REST_APL_ENDPOINT: z.string().optional(),
    REST_APL_TOKEN: z.string().optional(),
    OTEL_ENABLED: booleanSchema.optional().default("false"),
    OTEL_SERVICE_NAME: z.string().optional(),
    PORT: z.coerce.number().optional().default(3000),
    SECRET_KEY: z.string(),
    VERCEL_URL: z.string().optional(),
    DYNAMODB_MAIN_TABLE_NAME: z.string(),
    DYNAMODB_REQUEST_TIMEOUT_MS: z.coerce.number().default(5_000),
    DYNAMODB_CONNECTION_TIMEOUT_MS: z.coerce.number().default(2_000),
    AWS_REGION: z.string(),
    AWS_ACCESS_KEY_ID: z.string(),
    AWS_SECRET_ACCESS_KEY: z.string(),
    VERCEL_GIT_COMMIT_SHA: z.string().optional(),
    OTEL_ACCESS_TOKEN: z.string().optional(),
    VERCEL_ENV: z.string().optional(),
    REPOSITORY_URL: z.string().optional(),
    NEXT_RUNTIME: z.string().optional(),
    REQUEST_SECRET: z.string().optional(),
    FEED_CACHE_MAX_AGE: z.coerce.number().default(300),
    MAX_PARALLEL_CALLS: z.coerce.number().default(5),
    VARIANTS_PER_PAGE: z.coerce.number().default(50),
  },
  shared: {
    NODE_ENV: z.enum(["development", "production", "test"]).optional().default("development"),
    ENV: z.enum(["local", "development", "staging", "production"]).optional().default("local"),
  },
  runtimeEnv: {
    ALLOWED_DOMAIN_PATTERN: process.env.ALLOWED_DOMAIN_PATTERN,
    APL: process.env.APL,
    APP_API_BASE_URL: process.env.APP_API_BASE_URL,
    APP_IFRAME_BASE_URL: process.env.APP_IFRAME_BASE_URL,
    APP_LOG_LEVEL: process.env.APP_LOG_LEVEL,
    FILE_APL_PATH: process.env.FILE_APL_PATH,
    MANIFEST_APP_ID: process.env.MANIFEST_APP_ID,
    ENV: process.env.ENV,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    NODE_ENV: process.env.NODE_ENV,
    OTEL_ENABLED: process.env.OTEL_ENABLED,
    OTEL_SERVICE_NAME: process.env.OTEL_SERVICE_NAME,
    PORT: process.env.PORT,
    REST_APL_ENDPOINT: process.env.REST_APL_ENDPOINT,
    REST_APL_TOKEN: process.env.REST_APL_TOKEN,
    SECRET_KEY: process.env.SECRET_KEY,
    VERCEL_URL: process.env.VERCEL_URL,
    DYNAMODB_MAIN_TABLE_NAME: process.env.DYNAMODB_MAIN_TABLE_NAME,
    DYNAMODB_REQUEST_TIMEOUT_MS: process.env.DYNAMODB_REQUEST_TIMEOUT_MS,
    DYNAMODB_CONNECTION_TIMEOUT_MS: process.env.DYNAMODB_CONNECTION_TIMEOUT_MS,
    AWS_REGION: process.env.AWS_REGION,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    VERCEL_GIT_COMMIT_SHA: process.env.VERCEL_GIT_COMMIT_SHA,
    OTEL_ACCESS_TOKEN: process.env.OTEL_ACCESS_TOKEN,
    VERCEL_ENV: process.env.VERCEL_ENV,
    REPOSITORY_URL: process.env.REPOSITORY_URL,
    NEXT_RUNTIME: process.env.NEXT_RUNTIME,
    REQUEST_SECRET: process.env.REQUEST_SECRET,
    FEED_CACHE_MAX_AGE: process.env.FEED_CACHE_MAX_AGE,
    MAX_PARALLEL_CALLS: process.env.MAX_PARALLEL_CALLS,
    VARIANTS_PER_PAGE: process.env.VARIANTS_PER_PAGE,
  },
  isServer: typeof window === "undefined" || process.env.NODE_ENV === "test",
});
