name: saleor-app-products-feed_devcontainer
services:
  products-feed:
    image: products-feed
    command: sleep infinity # keeps docker container running
    build:
      context: ../..
      dockerfile: .devcontainer/products-feed/Dockerfile
    volumes:
      - "../..:/app"
      - "pnpm-store:/app/.pnpm-store"
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    ports:
      - 8000:8000
    volumes:
      - "dynamodb-data:/home/dynamodblocal/data"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    user: root # needed to write to volume

volumes:
  pnpm-store:
    driver: local
  dynamodb-data:
    driver: local