services:
  avatax:
    image: avatax
    command: sleep infinity
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - "..:/app"
      - "pnpm-store:/root/.pnpm-store"

  dynamodb:
    image: "amazon/dynamodb-local:latest"
    ports:
      - 8000:8000
    volumes:
      - "dynamodb-data:/home/dynamodblocal/data"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    user: root

volumes:
  dynamodb-data:
    driver: local
  pnpm-store:
    driver: local
