export const ENCRYPTED_METADATA_KEYS = {
  PUBLIC_TOKEN: "PUBLIC_TOKEN",
  CUSTOMER_CREATED_METRIC: "CUSTOMER_CREATED_METRIC",
  FULFILLMENT_CREATED_METRIC: "FULFILLMENT_CREATED_METRIC",
  ORDER_CREATED_METRIC: "ORDER_CREATED_METRIC",
  ORDER_FULLY_PAID_METRIC: "ORDER_FULLY_PAID_METRIC",
} as const;

export const ALL_ENCRYPTED_METADATA_KEYS = Object.values(ENCRYPTED_METADATA_KEYS);
