schema: graphql/schema.graphql
documents: [graphql/**/*.graphql, src/**/*.ts, src/**/*.tsx, scripts/migrations/**/*.ts]
extensions:
  codegen:
    overwrite: true
    generates:
      generated/graphql.ts:
        config:
          dedupeFragments: true
        plugins:
          - typescript
          - typescript-operations
          - typescript-urql:
              documentVariablePrefix: "Untyped"
              fragmentVariablePrefix: "Untyped"
          - typed-document-node
      generated/schema.graphql:
        plugins:
          - schema-ast
