name: Deployment
on: 
    workflow_dispatch:
      inputs: 
        app_name:
          type: choice
          required: true
          options:
            - slack
          description: What app to deploy
jobs:
  prepare:
    environment: Prod
    runs-on: ubuntu-latests
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.19.1
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Check linters
        run: pnpm build

  deploy: 
    environment: Prod
    runs-on: ubuntu-latests
    name: Deploy
    steps:
      - name: Deploy to Vecel
        run: echo "TODO $TOKEN"
