name: "App: Monitoring backend tests"

on:
  pull_request:
    paths:
      - "apps/monitoring/backend/**"

jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/monitoring/backend
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Run unit tests
        run: poetry run pytest
      - name: Run black
        run: poetry run black .
      - name: Run ruff
        run: poetry run ruff .
      - name: Run mypy
        run: poetry run mypy .
